# config.yaml
resources:
  - name: OLS
    endpoints:
      - "www.ebi.ac.uk/ols4*"
  - name: GENTAR_TRACKER_API
    endpoints:
      - "www.gentar.org/tracker-api*"
  - name: GENTAR_TRACKER
    endpoints:
      - "www.gentar.org/tracker*"
  - name: IMMUNOPHENOTYPE
    endpoints:
      - "www.immunophenotype.org*"
  - name: MI_DEV
    endpoints:
      - "wwwdev.ebi.ac.uk/mi*"
  - name: MI
    endpoints:
      - "www.ebi.ac.uk/mi*"
  - name: CANCER_MODELS
    endpoints:
      - "www.cancermodels.org*"
  - name: GWAS
    endpoints:
      - "www.ebi.ac.uk/gwas*"
      - "/pub/databases/gwas*"
