# config.yaml
 resources:
   - name: GENTAR_TRACKER_API
     destination-host: "www.gentar.org"
     endpoints:
      - "/tracker-api*"
   - name: GENTAR_TRACKER
     destination-host: "www.gentar.org"
     endpoints:
      - "/tracker*"
   - name: IMMUNOPHENOTYPE
     destination-host: "www.immunophenotype.org"
     endpoints:
      - "/*"
   - name: MI_DEV
     destination-host: "wwwdev.ebi.ac.uk"
     endpoints:
      - "/mi*"
   - name: MI
     destination-host: "www.ebi.ac.uk"
     endpoints:
      - "/mi*"
   - name: CANCER_MODELS
     destination-host: "www.cancermodels.org"
     endpoints:
      - "/*"
   - name: OLS
     destination-host: "www.ebi.ac.uk"
     endpoints:
       - "/ols4*"
   - name: GWAS
     destination-host: "www.ebi.ac.uk"
     endpoints:
       - "/gwas*"
       - "/pub/databases/gwas*"